config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:index, :show] do
    resources :medforms
  end

    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hospital.rb
class Hospital < User

end

app/models/medform.rb
class Medform < ApplicationRecord
  belongs_to :patient, :dependent => :destroy
end

app/models/patient.rb
class Patient < User
    has_many :medforms
end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  private
  def confirmation_period_valid?
    return true
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  devise_group :user, contains: [:patient, :hospital]
  before_action :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
     if current_user.type == "patient"
       render "/home/patients"
     elsif current_user.type == "hospital"
       render "/home/hospitals"
    else
      redirect_to new_patient_registration
    end
  end
end

app/controllers/hospitals/registrations_controller.rb
class Hospitals::RegistrationsController < Devise::RegistrationsController
  def show
    @hospital = Hospital.find(params[:id])
  end
end

app/controllers/hospitals/sessions_controller.rb
class Hospitals::SessionsController < Devise::SessionsController
  def show
    @hospital = Hospital.find(params[:id])
  end
end

app/controllers/medforms_controller.rb
class MedformsController < UsersController
  def new
   @patient = Patient.find(params[:user_id])
   @medform = Medform.new
  end
  def create
    @medform = @patient.medforms.new(medform_params)
if @medform.save && medform_params.first_name.present?
  @patient.first_name = medform_params.first_name
  @patient.last_name = medform_params.last_name
  @patient.id_string = medform_params.id_string
  @patient.address = medform_params.address
  @patient.city = medform_params.city
  @patient.country = medform_params.country
  @patient.postal_code = medform_params.postal_code
  @patient.phone = medform_params.phone
  @patient.save
  redirect_to user_path(@patient)
elsif @medform.save
  redirect_to user_path(@patient)
else
  render :new
end
end

def show
  # @reviews = Review.find_by(place_id: params[:id])
  # @review = current_user.reviews.new
  @place = Place.find(params[:id])
  render template: 'places/show'
end

def edit
@medforms = Medform.find(params[:id])


end

def update
@medforms = Medform.find(params[:id])
if @medform.update && medform_params.first_name.present?
  @patient.first_name = medform_params.first_name
  @patient.last_name = medform_params.last_name
  @patient.id_string = medform_params.id_string
  @patient.address = medform_params.address
  @patient.city = medform_params.city
  @patient.country = medform_params.country
  @patient.postal_code = medform_params.postal_code
  @patient.save
  flash[:success] = 'You have successfully updated your form'
  redirect_to @medform
elsif @medform.update
  flash[:success] = 'You have successfully updated your form'
  redirect_to @medform

else
flash[:danger] = 'Error updating form'
render :edit
end
end



  private
      # Using a private method to encapsulate the permissible parameters is
      # a good pattern since you'll be able to reuse the same permit
      # list between create and update. Also, you can specialize this method
      # with per-user checking of permissible attributes.
      def medform_params
        params.require(:medform).permit(:first_name, :last_name, :id_string, :address, :city, :country, :postal_code, :phone, :birth_date, :primary_language, :gender, :medications, :allergies, :hospitalisations, :conditions, :pdf)
      end
    end

app/controllers/patients/registrations_controller.rb
class Patients::RegistrationsController < Devise::RegistrationsController
def new
@patient = Patient.new

end

  def show
    @patient = Patient.find(params[:id])
    @medforms = Medform.where(user_id: @patient.id)
  end
end

app/controllers/patients/sessions_controller.rb
class Patients::SessionsController < Devise::SessionsController
def new
render 'patients/sessions/new'
end

  def show
    @patient = Patient.find(params[:id])
    @medforms = Medform.where(user_id: @patient.id)
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  def show
  end
  def new
redirect_to new_patient_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all #admin only
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forms_helper.rb
module FormsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/hospitals_helper.rb
module HospitalsHelper
end

app/helpers/patient_helper.rb
module PatientHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/hospitals.html.erb
<div class="container-fluid" role="main">
  <div class="jumbotron">

  <h1 class="text-center">Find your patient here!</h1>
  <p class="text-center">Easily locate and upload your patients documents to our secure database.<strong>√</strong>  </p>
  <p class="text-center">No longer deal with clients upset about being forced to fill out an inconvenient form while sick.<strong>√</strong>  </p>
  <p class="text-center">Every 6 months, your patients will be asked to update their main form to streamline the check-in process.</p>
  <p class="text-center">Type in your patients name and or social security to look them up.</p>
    <p class="text-center">You'll need their generated password to access their documents :)<strong>√</strong></p>
    <a class="button medred-background btn btn-block" href="/patients/<%=current_user.id%>/medforms/new">Take 20 minutes to fill out your last form, ever!</a>
  </div>
</div>

app/views/home/index.html.erb
<div class="container-fluid" role="main">
  <div class="jumbotron">
    
  <h1 class="text-center">Fill out your last medical form here!</h1>
  <p class="text-center">Are you tired of filling out those long forms each time you visit a doctor's office? <strong>√</strong>  </p>
  <p class="text-center">Do you want to have access to your personal medical forms? <strong>√</strong>  </p>
  <p class="text-center">We have created a double-password protected database that allows you and your chosen medical practitioners to have access to your documents. </p>
  <p class="text-center">So, let's sign-up and fill out your last doctor's form ever :)</p>
    <a class="button medred-background btn btn-block" href="/users/<%=current_user.id%>/medforms/new">Take 20 minutes to fill out your last form, ever!</a>
  </div>
</div>

app/views/home/patients.html.erb
<div class="container-fluid" role="main">
  <div class="jumbotron">

  <h1 class="text-center">Fill out your last medical form here!</h1>
  <p class="text-center">Are you tired of filling out those long forms each time you visit a doctor's office? <strong>√</strong>  </p>
  <p class="text-center">Do you want to have access to your personal medical forms? <strong>√</strong>  </p>
  <p class="text-center">We have created a double-password protected database that allows you and your chosen medical practitioners to have access to your documents. </p>
  <p class="text-center">So, let's sign-up and fill out your last doctor's form ever :)</p>
    <a class="button medred-background btn btn-block" href="/patients/<%=current_user.id%>/medforms/new">Take 20 minutes to fill out your last form, ever!</a>
  </div>
</div>

app/views/hospitals/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/forms/_newoverview.html.erb
<div class="container1">

    <div class="row">
        <div class="col-sm-6 col-md-12">
            <div class="thumbnail">

                <div class="text-field">
                    <%= form.label :first_name %>
                    <%= form.text_field :first_name, class: "form-control" %>
                    <div class="text-field">
                        <%= form.label :last_name %>
                        <%= form.text_area :last_name, class: "form-control" %>
                    </div>

                    <div class="text-field">
                        <%= form.label 'Type your personal identification number here.'%>
                        <%= form.text_area :id_string, class: "form-control" %>
                    </div>

                    <div class="text-field">
                        <%= form.label :address %>
                        <%= form.text_field :address, class: "form-control" %>
                    </div>

                    <div class="text-field">
                        <%= form.label :city %>
                        <%= form.number_field :city, class: "form-control" %>
                    </div>

                    <div class="text-field">
                        <%= form.label :country %>
                        <%= form.text_area :country, class: "form-control" %>
                    </div>

                    <div class="text-field">
                        <%=form.label :postal_code %>
                        <%=form.text_area :postal_code, class: "form-control" %>

                    </div>

                    <div class="text-field">
                        <%= form.label "phone number" %>
                        <%= form.text_area :phone, class: "form-control" %>
                    </div>

                    <div class="date-field">
                        <%= form.label :birth_date%>
                        <%= form.text_area :birth_date, class: "form-control" %>
                    </div>

                    <div class="text-field">
                        <%= form.label "Which language do you prefer?
                        Your caretaker will provide you with a translator where applicable and possible." %>
                        <%= form.text_area :primary_language, class: "form-control" %>
                    </div>

                    <div class="text-field">
                        <%= form.label :gender %>
                        <%= form.text_area :gender, class: "form-control" %>
                    </div>

                    <div class="text-field">
                        <%= form.label "List any medications that you are currently taking" %>
                        <%= form.text_area :medications, class: "form-control" %>
                    </div>

                    <div class="text-field">
                        <%= form.label "List any allergies here, especially allergies of any medications" %>
                        <%= form.text_area :allergies, class: "form-control" %>
                    </div>

                    <div class="text-field">
                        <%= form.label "Please tell us about any previous hospitilisations - including, but not limited to, surgeries and emergency room visits" %>
                        <%= form.text_area :hospitilisations, class: "form-control" %>
                    </div>

                    <div class="text-field">
                        <%= form.label "Are there any other conditions that you could benefit from telling your medical practitioner about? If so, list them here." %>
                        <%= form.text_area :phone, class: "form-control" %>
                    </div>

                    <div class="hidden-field">
                        <%= form.hidden_field :form_name, :value => "Overview"%>
                    </div>

                    <div class="file-field">
                        <%= form.label "You can upload an image of yourself to aid in the security of your account"  %>
                        <%= form.file_field :avatar, class: "form-control" %>
                    </div>
                    <br>
                    <div class="submit-field">
                        <%= form.submit %>
                    </div>

                </div>
            </div>
        </div>
    </div>

    <p><%=link_to "Home", users_path(current_user)%><br>
        <%=link_to "Index", places_path%></p>

</div>
</div>

app/views/users/show.html.erb
<% @medforms.each do |medform| %>
<%= link_to user_form_path(@user, medform) do%>
<p class="padding"><%=image_tag medform.image.thumb.url %></p>
<% end %>